-- Auto-generated by data/bootstrap.py
-- Run this once at the start of a SQL session/tab.

ATTACH 'data/q001.duckdb' AS q001;
USE q001.main;

SHOW TABLES;
select * from users;
select * from activity;